name: Deployed to GitHub Pages
on:
  workflow_dispatch:
    branches:
      - master
env:
  NODE-ENV: production
  VUE_APP_API_KEY: ${{secrets.VUE_APP_API_KEY}}
  VUE_APP_FIREBASE_API_KEY: ${{secrets.VUE_APP_FIREBASE_API_KEY}}
  VUE_APP_FIREBASE_DATABASE_URL: ${{secrets.VUE_APP_FIREBASE_DATABASE_URL}}
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 7.25.0
      - name: install deps
        run: pnpm install
      - name: build app
        run: pnpm build




